# Generated by Django 6.0.4 on 2026-04-13 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornal', '0002_categoria_artigo_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='visualizacoes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
